language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
sudo: required
install:
    - sudo apt-get install libxml-libxml-perl 
    - cpanm --with-all-features --notest --skip-satisfied --installdeps .
env: RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1
after_success:
    - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
    - perl Build.PL && ./Build build && cover -test -report coveralls
